### ISSUE TITLE
Issue in running 'scripts/pipeline.py'

### ISSUE THREAD

**Issue by jason2133** [rotot0/tab-ddpm#10]
Hi, Thanks for uploading the code with the paper.

I just wanted to work this code, 
After setting up the environment using conda and downloading this code and the dataset, I ran the TabDDPM pipeline as you wrote on GitHub Repository.
```
python scripts/pipeline.py --config exp/churn2/ddpm_cb_best/config.toml --train --sample
```

However, the commander made some error.
```
(tddpm) C:\Users\Desktop\Code\tab-ddpm-main>python scripts/pipeline.py --config exp/churn2/ddpm_cb_best/config.toml --train --sample
Traceback (most recent call last):
  File "C:\Users\Desktop\Code\tab-ddpm-main\scripts\pipeline.py", line 5, in <module>
    from train import train
  File "C:\Users\Desktop\Code\tab-ddpm-main\scripts\train.py", line 6, in <module>
    from tab_ddpm import GaussianMultinomialDiffusion
ModuleNotFoundError: No module named 'tab_ddpm'
```

May I know the reason why tab_ddpm is not imported?
I did not modify any code, and just wanted to work this code.
I just turned the code, but I cannot understand why the error is coming out.

**Comment by jason2133** [comment]
Oh, I found the reason why the error is coming out. It was a simple cause and I solved this problem. Therefore, I close this issue. Once again, Thanks for uploading the code with the paper.

**Comment by SvenGroen** [comment]
@jason2133 I am keep getting the same error as you did when trying to run the script in the cloud. Not getting the error when running it locally. I think it has to do with not setting the Pythonpath correctly.
How exactly did you solve this issue? what was your solution?

**Comment by dajiaohuang** [comment]
same problem, how did you solve it?

**Comment by dajiaohuang** [comment]
got it, just move lib and tab_ddpm into the dir script.
