### ISSUE TITLE
'type' object is not iterable. Raised from tab_ddpm\lib\metrics.py", line 37, in MetricsReport

### ISSUE THREAD

**Issue by froggyis** [rotot0/tab-ddpm#14]
First I would like to thank for the sharing of the code, the idea of using diffusion model to solve tabular data is mind blowing.

I am trying to reproduce the project after I gather all the package I need
I run the command 
`python scripts/pipeline.py --config exp/churn2/ddpm_cb_best/config.toml --train --sample`

and it raise the error message

>   File "D:\Dev\tab_ddpm\scripts\pipeline.py", line 5, in <module>
>     from train import train
>   File "D:\Dev\tab_ddpm\scripts\train.py", line 8, in <module>
>     from utils_train import get_model, make_dataset, update_ema
>   File "D:\Dev\tab_ddpm\scripts\utils_train.py", line 3, in <module>
>     import lib
>   File "D:\Dev\tab_ddpm\lib\__init__.py", line 8, in <module>
>     from .data import *  # noqa
>   File "D:\Dev\tab_ddpm\lib\data.py", line 22, in <module>
>     from .metrics import calculate_metrics as calculate_metrics_
>   File "D:\Dev\tab_ddpm\lib\metrics.py", line 17, in <module>
>     class MetricsReport:
>   File "D:\Dev\tab_ddpm\lib\metrics.py", line 37, in MetricsReport
>     def get_splits_names(self) -> list(str):
> TypeError: 'type' object is not iterable

I have googled it, but most of the answer tell me to rewrite the class object. I still have no clue how to fix the bus

**Comment by rotot0** [comment]
Hi!
I guess you are using an old version of python. Use python3.9.7 or newer version.

**Comment by rotot0** [comment]
Also, I noticed you have `list(str)` with round bracket in your code

See, https://github.com/rotot0/tab-ddpm/blob/main/lib/metrics.py#L37

**Comment by froggyis** [comment]
I ask a pretty stupid question. Thanks for the fast reply.
