### ISSUE TITLE
Dataset link not valid 

### ISSUE THREAD

**Issue by hadikoub** [rotot0/tab-ddpm#24]
Hello, I'm getting an access error to the provided dataset link it seems the link is no longer valid: `https://www.dropbox.com/s/rpckvcs3vx7j605/data.tar?dl=0 `

Is it possible to have a valid link for the used dataset?

Thank you.

**Comment by rotot0** [comment]
Hello, the link works fine for me. Maybe you should try VPN. Not sure, though.
But I have also uploaded it [here](https://drive.google.com/file/d/16p7PIv8cpPMBkE3fS1dQt1pcT1LVJyOX/view?usp=sharing)
