### ISSUE TITLE
Question about tune evaluation models

### ISSUE THREAD

**Issue by yuntaod** [rotot0/tab-ddpm#26]
Hi,

Thanks for your wonderfull paper and code! I have a small question about the evulation process:

In my understanding, `tuned_models/ ` stores the tuned parameters for each evaluation model (CatBoost or MLP) **on real data**, and when we tune a new synthesis method like Tab-DDPM, we just use tuned parameters to evaluate the synthesized data? Is that right?

If so, I am wondering whether it is possible that for synthesized data, there are better parameters that can reach the better performance on CatBoost or MLP?

Thanks and looking forward to your rely!

**Comment by rotot0** [comment]
Hi,

Yes, you are right about tuned parameters. As for tuning on synthesized data, we tried that and there was no substantial difference. 

Thanks for your question!
