### ISSUE TITLE
Reconstruct CSV with column names

### ISSUE THREAD

**Issue by andrewnc** [rotot0/tab-ddpm#3]
Great work here, I'm curious if there is a supported way to reconstruct the synthetic data into a single DataFrame / CSV with the original column names preserved?

**Comment by rotot0** [comment]
Thanks a lot. Unfortunately, there is no such way.

You can find [here](https://github.com/Yura52/tabular-dl-num-embeddings/blob/main/bin/datasets.py) how some of the original datasests (`adult`, `california`, `fb-comments`, `gesture`, `higgs-small`, `house`) were spliited/transformed into `X_{num|cat}_{train|val|test}.npy` format. But there is no script to transform it back to the original format.

I may add this in the future but it's unlikely.
