### ISSUE TITLE
xyz_cv.json

### ISSUE THREAD

**Issue by Oefuli** [rotot0/tab-ddpm#31]
What are the xyz_cv.json files in the tuned_models folder for?

**Comment by rotot0** [comment]
Hyperparameters, tuned using cross-validation, for evaluation model. Using these hparams we calculate ML utility metric.

**Comment by JiangLei1012** [comment]
@rotot0 How was the xyz_cv.json files generated?

**Comment by rotot0** [comment]
> @rotot0 How was the xyz_cv.json files generated?

`scripts/tune_evaluation_model.py` with `tune_type="cv"`
