### ISSUE TITLE
Code for applying your approach to own datasets/dataframes

### ISSUE THREAD

**Issue by Timbimjim** [rotot0/tab-ddpm#4]
Hello, I'am struggling adapting your code to apply the principals on my own datasets. Could you add a short explanation on how to do this?

thanks a lot

**Comment by rotot0** [comment]
Hello, you can find examples [here](https://github.com/Yura52/tabular-dl-num-embeddings/blob/main/bin/datasets.py). Let me know if it is still not clear :)

**Comment by froggyis** [comment]
@Timbimjim  Hi there, I am also trying to apply the model on my own datasets, Can I have your email or any social id to discuss the detail?
