### ISSUE TITLE
Please help me, there is an issue with loading the dataset.

### ISSUE THREAD

**Issue by happyxin5** [rotot0/tab-ddpm#42]
(tddpm) D:\Study\code\tab-ddpm-main>wget "https://www.dropbox.com/s/rpckvcs3vx7j605/data.tar?dl=0" -O data.tar
--2024-09-25 20:50:31--  https://www.dropbox.com/s/rpckvcs3vx7j605/data.tar?dl=0
Resolving www.dropbox.com (www.dropbox.com)... 75.126.124.162, 2a03:2880:f136:83:face:b00c:0:25de
Connecting to www.dropbox.com (www.dropbox.com)|75.126.124.162|:443... failed: Unknown error.
Connecting to www.dropbox.com (www.dropbox.com)|2a03:2880:f136:83:face:b00c:0:25de|:443... failed: Bad file descriptor.
Have you encountered this situation before? I would be extremely grateful if you could help me!

**Comment by rotot0** [comment]
Please, see this (https://github.com/yandex-research/tab-ddpm/issues/24) issue. Reopen this one if it doesn't help.
