### ISSUE TITLE
lib/util.py

### ISSUE THREAD

**Issue by sas8465** [rotot0/tab-ddpm#5]
Hey guys,

I really appreciate your code and implementation. I am trying to reconstruct the experiments. However, there is a library called 'zero' that is used in the util file that does not have the attributes used. I looked into the documentation and it doesn't exist there either. Do you know if this is a custom library or if it using a previous version? I also looked through the requirements.txt and 'zero' is not present there either. This is where it is used in the code:

lib/util.py:
22. import zero
49. class Timer(zero.Timer):
271. 'gpus': zero.hardware.get_gpus_info(),  

Thanks in advance for your time.

Best regards

**Comment by sas8465** [comment]
I think I solved the issue by looking at the delu library (https://github.com/Yura52/delu)
and changing line 22 above to import delu as zero to not have to change other things in the code. It seems to have worked.

**Comment by chaojieji** [comment]
> I think I solved the issue by looking at the delu library (https://github.com/Yura52/delu) and changing line 22 above to import delu as zero to not have to change other things in the code. It seems to have worked.

It works for me! Tks!
